# Generated by Django 4.1.1 on 2022-09-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseNumber', models.PositiveIntegerField(default=0)),
                ('caseTitle', models.CharField(max_length=200)),
                ('caseTentDate', models.DateField(default=None, null=True, verbose_name='Date')),
                ('caseFilingDate', models.DateField(default=None, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CasePersonRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeNumber', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataEntry.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataEntry.person')),
                ('personType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataEntry.persontype')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='caseType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DataEntry.casetype'),
        ),
    ]
