# Generated by Django 4.1.1 on 2022-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseFilingDate',
            field=models.DateField(default=None, null=True, verbose_name='Filing Date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='caseTentDate',
            field=models.DateField(default=None, null=True, verbose_name='Tent Date'),
        ),
    ]
